id: I5CD46981
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W1KG10375
  source: bdrc.io
  batch_id: batch003
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.7
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-11-01T09:34:59.717455+00:00'
last_modified: '2022-11-01T09:34:59.717461+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10375
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessFairUse
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10375
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཚུལ་ཁྲིམས་རྒྱལ་མཚན།
  languages:
  - bo
  author: ན་ལེནྡྲ་འི་མཁན་པོ་ཚུལ་ཁྲིམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9952884127959685
  ocr_word_median_confidence_index: 1.0
quality: null
bases:
  I1KG10400:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10400
      total_pages: 480
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG10400.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9952884127959685
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
